$(document).ready(function(){
	$("body").removeClass("animatedOne");
	$('#video').get(0).pause();
var swiper = new Swiper(".swiper-container",{
	direction:"vertical",
	effect:"overflow",
	onSlideChangeEnd:function(swiper){
		switch (swiper.activeIndex){
						case 0:{
							$("body").removeClass("animatedOne");
							$("body").removeClass("animatedTwo");
							$("body").removeClass("animatedThree");
							$("body").removeClass("animatedFour");
							$("body").removeClass("animatedFive");
							$("body").removeClass("animatedSix");
							$("body").removeClass("animatedSeven");
							$("body").removeClass("animatedEight");
							$("body").removeClass("animatedNine");
							$("body").removeClass("animatedTen");
							$("body").removeClass("animatedEleven");
							$("body").removeClass("animatedTel");
							$("body").removeClass("animatedShisan");
							$("body").removeClass("animatedFourteen");
							$("body").removeClass("animatedFiveteen");
							$("body").removeClass("animatedSixteen");
							$("body").removeClass("animatedSeventeen");
							$("body").removeClass("animatedEightteen");
							$("body").removeClass("animatedNineteen");
							$("body").removeClass("animatedTwti");
							$("body").addClass("animatedOne");
							break;
						}
						case 1:{
							$("body").removeClass("animatedOne");
							$("body").removeClass("animatedTwo");
							$("body").removeClass("animatedThree");
							$("body").removeClass("animatedFour");
							$("body").removeClass("animatedFive");
							$("body").removeClass("animatedSix");
							$("body").removeClass("animatedSeven");
							$("body").removeClass("animatedEight");
							$("body").removeClass("animatedNine");
							$("body").removeClass("animatedTen");
							$("body").removeClass("animatedEleven");
							$("body").removeClass("animatedTel");
							$("body").removeClass("animatedShisan");
							$("body").removeClass("animatedFourteen");
							$("body").removeClass("animatedFiveteen");
							$("body").removeClass("animatedSixteen");
							$("body").removeClass("animatedSeventeen");
							$("body").removeClass("animatedEightteen");
							$("body").removeClass("animatedNineteen");
							$("body").removeClass("animatedTwti");
							$("body").addClass("animatedTwo");
							break;	
						}
						case 2:{
							$("body").removeClass("animatedOne");
							$("body").removeClass("animatedTwo");
							$("body").removeClass("animatedThree");
							$("body").removeClass("animatedFour");
							$("body").removeClass("animatedFive");
							$("body").removeClass("animatedSix");
							$("body").removeClass("animatedSeven");
							$("body").removeClass("animatedEight");
							$("body").removeClass("animatedNine");
							$("body").removeClass("animatedTen");
							$("body").removeClass("animatedEleven");
							$("body").removeClass("animatedTel");
							$("body").removeClass("animatedShisan");
							$("body").removeClass("animatedFourteen");
							$("body").removeClass("animatedFiveteen");
							$("body").removeClass("animatedSixteen");
							$("body").removeClass("animatedSeventeen");
							$("body").removeClass("animatedEightteen");
							$("body").removeClass("animatedNineteen");
							$("body").removeClass("animatedTwti");
							$("body").addClass("animatedThree");
							break;
						}
						case 3:{
							$("body").removeClass("animatedOne");
							$("body").removeClass("animatedTwo");
							$("body").removeClass("animatedThree");
							$("body").removeClass("animatedFour");
							$("body").removeClass("animatedFive");
							$("body").removeClass("animatedSix");
							$("body").removeClass("animatedSeven");
							$("body").removeClass("animatedEight");
							$("body").removeClass("animatedNine");
							$("body").removeClass("animatedTen");
							$("body").removeClass("animatedEleven");
							$("body").removeClass("animatedTel");
							$("body").removeClass("animatedShisan");
							$("body").removeClass("animatedFourteen");
							$("body").removeClass("animatedFiveteen");
							$("body").removeClass("animatedSixteen");
							$("body").removeClass("animatedSeventeen");
							$("body").removeClass("animatedEightteen");
							$("body").removeClass("animatedNineteen");
							$("body").removeClass("animatedTwti");
							$("body").addClass("animatedFour");
							break;
						}
						case 4:{
							$("body").removeClass("animatedOne");
							$("body").removeClass("animatedTwo");
							$("body").removeClass("animatedThree");
							$("body").removeClass("animatedFour");
							$("body").removeClass("animatedFive");
							$("body").removeClass("animatedSix");
							$("body").removeClass("animatedSeven");
							$("body").removeClass("animatedEight");
							$("body").removeClass("animatedNine");
							$("body").removeClass("animatedTen");
							$("body").removeClass("animatedEleven");
							$("body").removeClass("animatedTel");
							$("body").removeClass("animatedShisan");
							$("body").removeClass("animatedFourteen");
							$("body").removeClass("animatedFiveteen");
							$("body").removeClass("animatedSixteen");
							$("body").removeClass("animatedSeventeen");
							$("body").removeClass("animatedEightteen");
							$("body").removeClass("animatedNineteen");
							$("body").removeClass("animatedTwti");
							$("body").addClass("animatedFive");
							break;
						}
						case 5:{
							$("body").removeClass("animatedOne");
							$("body").removeClass("animatedTwo");
							$("body").removeClass("animatedThree");
							$("body").removeClass("animatedFour");
							$("body").removeClass("animatedFive");
							$("body").removeClass("animatedSix");
							$("body").removeClass("animatedSeven");
							$("body").removeClass("animatedEight");
							$("body").removeClass("animatedNine");
							$("body").removeClass("animatedTen");
							$("body").removeClass("animatedEleven");
							$("body").removeClass("animatedTel");
							$("body").removeClass("animatedShisan");
							$("body").removeClass("animatedFourteen");
							$("body").removeClass("animatedFiveteen");
							$("body").removeClass("animatedSixteen");
							$("body").removeClass("animatedSeventeen");
							$("body").removeClass("animatedEightteen");
							$("body").removeClass("animatedNineteen");
							$("body").removeClass("animatedTwti");
							$("body").addClass("animatedSix");
							break;
						}
						case 6:{
							$("body").removeClass("animatedOne");
							$("body").removeClass("animatedTwo");
							$("body").removeClass("animatedThree");
							$("body").removeClass("animatedFour");
							$("body").removeClass("animatedFive");
							$("body").removeClass("animatedSix");
							$("body").removeClass("animatedSeven");
							$("body").removeClass("animatedEight");
							$("body").removeClass("animatedNine");
							$("body").removeClass("animatedTen");
							$("body").removeClass("animatedEleven");
							$("body").removeClass("animatedTel");
							$("body").removeClass("animatedShisan");
							$("body").removeClass("animatedFourteen");
							$("body").removeClass("animatedFiveteen");
							$("body").removeClass("animatedSixteen");
							$("body").removeClass("animatedSeventeen");
							$("body").removeClass("animatedEightteen");
							$("body").removeClass("animatedNineteen");
							$("body").removeClass("animatedTwti");
							$("body").addClass("animatedSeven");
							break;
						}
						case 7:{
							$("body").removeClass("animatedOne");
							$("body").removeClass("animatedTwo");
							$("body").removeClass("animatedThree");
							$("body").removeClass("animatedFour");
							$("body").removeClass("animatedFive");
							$("body").removeClass("animatedSix");
							$("body").removeClass("animatedSeven");
							$("body").removeClass("animatedEight");
							$("body").removeClass("animatedNine");
							$("body").removeClass("animatedTen");
							$("body").removeClass("animatedEleven");
							$("body").removeClass("animatedTel");
							$("body").removeClass("animatedShisan");
							$("body").removeClass("animatedFourteen");
							$("body").removeClass("animatedFiveteen");
							$("body").removeClass("animatedSixteen");
							$("body").removeClass("animatedSeventeen");
							$("body").removeClass("animatedEightteen");
							$("body").removeClass("animatedNineteen");
							$("body").removeClass("animatedTwti");
							$("body").addClass("animatedEight");
							break;
						}					
						default:{
							break;
					}
			};
//				检索当前第几页
		console.log(swiper.activeIndex);
	}	
});
});
